<!DOCTYPE html> 
<html> 
<head> 
<link rel="icon" href="images/logo222.png" type="image/gif" sizes="16x16"> 
36 
<title>Hierarchical Transmission</title> 
<link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="all" /> 
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
<script src="js/jquery.min.js"></script> 
<!-- Custom Theme files --> 
<!--theme-style--> 
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" /> 
<!--//theme-style--> 
<meta name="viewport" content="width=device-width, initial-scale=1"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<meta name="keywords" content="Spa Center Responsive web template, Bootstrap Web 
Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns 
for Nokia, Samsung, LG, 
SonyEricsson, Motorola web design" /> 
<script 
type="application/x-javascript"> 
addEventListener("load", 
function() 
{ 
setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } 
</script> 
<!----> 
<script src="js/bootstrap.min.js"></script> 
<link href='//fonts.googleapis.com/css?family=Lora:400,700' rel='stylesheet' type='text/css'> 
<link 
href='//fonts.googleapis.com/css?family=Raleway:400,200,100,300,500,600,700,800,900' 
rel='stylesheet' type='text/css'> 
<style type="text/css"> 
<!-- 
.style3 {color: #000000} 
.button { 
border-radius: 4px; 
background-color:#4F92FF; 
border: none; 
color:#000000; 
text-align: center; 
font-size: 28px; 
font-weight:bold; 
37 
padding: 20px; 
width: 200px; 
transition: all 0.5s; 
cursor: pointer; 
margin: 5px; 
} 
.button span { 
cursor: pointer; 
display: inline-block; 
position: relative; 
transition: 0.5s; 
} 
.button span:after { 
content: '\00bb'; 
position: absolute; 
opacity: 0; 
top: 0; 
right: -20px; 
transition: 0.5s; 
} 
.button:hover span { 
padding-right: 25px; 
} 
.button:hover span:after { 
opacity: 1; 
right: 0; 
} 
.style7 {font-size: 28px; font-weight: bold; } 
.style9 { 
color: #000000; 
font-size: 18px; 
38 
font-weight: bold; 
} 
.style12 {font-size: 18px} 
.style4 {width:200px; height:35px;} 
.style66 {width:200px; height:50px;} --> 
</style> 
</head> 
<body> 
<div class="header head-top"> 
<nav class="navbar navbar-default animated wow fadeInLeft" data-wow- 
duration="1000ms" data-wow-delay="500ms"> 
<div class="container"> 
<div class="container-fluid"> 
<!-- Brand and toggle get grouped for better mobile display --> 
<div class="navbar-header"> 
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> 
<span class="sr-only">Toggle navigation</span> 
<span class="icon-bar"></span> 
<span class="icon-bar"></span> 
<span class="icon-bar"></span> 
</button> 
</div> 
<!-- Collect the nav links, forms, and other content for toggling --> 
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> 
<form class="navbar-form navbar-left" role="search"> 
<div class="form-group"> 
<input 
type="text" 
class="form-control 
form-cont" 
onFocus="this.value='';" onBlur="if (this.value == '') {this.value ='Search';}"> 
</div> 
value="Search" 
39 
<button type="submit" class="btn-search"></button> 
</form> 
<ul class="nav navbar-nav cl-effect-8"> 
<li ><a class="active" href="index.php">Home </a></li> 
<li><a href="ulogin.php">User</a></li> 
<li><a href="alogin.php">Admin</a></li> 
<li><a href="#">About</a></li> 
<li><a href="contact.php">Contact</a></li> 
</ul> 
</div><!-- /.navbar-collapse --> 
</div><!-- /.container-fluid --> 
</div> 
</nav> 
<!-- start search--> 
<div class="logo animated wow shake" data-wow-duration="1000ms" data- 
wow-delay="500ms"> 
<a href="index.html"><img src="images/logo1.png" alt=""></a> 
</div> 
</div> 
<div class="container"> 
<div class="gallery" > 
<h1>User<span class="style3">Register</span></h1> 
<div class="gallery-top wow fadeInDown animated" data-wow-delay=".5s"> 
<div class="clearfix"></div> 
</div>  
 
<div class="gallery-top wow fadeInDown animated" data-wow-delay=".5s"> 
<div class="clearfix"> 
<form name="form1" method="post" action=""> 
<p>&nbsp;</p> 
<table width="618" height="502" border="0" align="center"> 
40 
<tr> 
<td width="15">&nbsp;</td> 
<td width="15">&nbsp;</td> 
<td width="15">&nbsp;</td> 
<td width="205">&nbsp;</td> 
<td width="24"><div align="center"><span class="style12"></span></div></td> 
<td width="232">&nbsp;</td> 
<td width="15">&nbsp;</td> 
<td width="15">&nbsp;</td> 
<td width="15">&nbsp;</td> 
<td width="25">&nbsp;</td> 
</tr> 
<tr> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td><span class="style7">Name</span></td> 
<td><div align="center"><span class="style9">:</span></div></td> 
<td><input name="name" type="text" class="style4" id="name"></td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
</tr> 
<tr> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td><span class="style7">Gender</span></td> 
<td><div align="center"><span class="style9">:</span></div></td> 
<td><label> 
<input name="gender" type="radio" value="Male"> 
<span class="style7">Male 
<input name="gender" type="radio" value="Female"> 
41 
Female</span></label></td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
</tr> 
<tr> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td><span class="style7">MobileNumber</span></td> 
<td><div align="center"><span class="style9">:</span></div></td> 
<td><input name="mnumber" type="text" class="style4" id="mnumber"></td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
</tr> 
<tr> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td><span class="style7">EmailId</span></td> 
<td><div align="center"><span class="style9">:</span></div></td> 
<td><input name="emailid" type="text" class="style4" id="emailid"></td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
</tr> 
<tr> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
42 
<td><span class="style7">Address</span></td> 
<td><div align="center"><span class="style9">:</span></div></td> 
<td><input name="address" type="text" class="style4" id="address"></td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
</tr> 
<tr> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td><span class="style7">UserName</span></td> 
<td><div align="center"><span class="style9">:</span></div></td> 
<td><input name="uname" type="text" class="style4" id="uname"></td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
</tr> 
<tr> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td><span class="style7">Password</span></td> 
<td><div align="center"><span class="style9">:</span></div></td> 
<td><input name="pwd" type="password" class="style4" id="pwd"></td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
</tr> 
<tr> 
<td>&nbsp;</td> 
43 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td><div align="center"><span class="style12"></span></div></td> 
<td><input 
name="btn" 
value="Register"></td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
<td>&nbsp;</td> 
</tr> 
</table> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
<p>&nbsp;</p> 
</form> 
</div> 
</div> 
</div> 
</div> 
<!----> 
type="submit" 
class="style66" 
id="btn" 
44 
<div 
class="modal 
fade" 
id="image-gallery" 
tabindex="-1" 
role="dialog" 
aria- 
labelledby="myModalLabel" aria-hidden="true"> 
<div class="modal-dialog"> 
<div class="modal-content"> 
<div class="modal-header"> 
<button 
type="button" 
class="close" 
data-dismiss="modal"><span 
hidden="true">×</span><span class="sr-only">Close</span></button> 
<h4 class="modal-title" id="image-gallery-title"></h4> 
</div> 
<div class="modal-body"> 
<img id="image-gallery-image" class="img-responsive" src=""> 
</div> 
<div class="modal-footer"> 
<div class="col-md-2"> 
<button 
type="button" 
class="btn 
btn-primary" 
aria- 
id="show-previous- 
image">Previous</button> 
</div> 
<div class="col-md-8 text-justify" id="image-gallery-caption"> 
This text will be overwritten by jQuery 
</div> 
<div class="col-md-2"> 
<button 
type="button" 
default">Next</button> 
</div> 
</div> 
</div> 
</div> 
</div> 
<script> 
$(document).ready(function(){ 
id="show-next-image" 
class="btn 
btn- 
45 
loadGallery(true, 'a.thumbnail'); 
//This function disables buttons when needed 
function disableButtons(counter_max, counter_current){ 
$('#show-previous-image, #show-next-image').show(); 
if(counter_max == counter_current){ 
$('#show-next-image').hide(); 
} else if (counter_current == 1){ 
$('#show-previous-image').hide(); 
} 
} 
/** 
* 
* @param setIDs 
Sets IDs when DOM is loaded. If using a PHP counter, set to false. 
* @param setClickAttr Sets the attribute for the click handler. 
*/ 
function loadGallery(setIDs, setClickAttr){ 
var current_image, 
selector, 
counter = 0; 
$('#show-next-image, #show-previous-image').click(function(){ 
if($(this).attr('id') == 'show-previous-image'){ 
current_image--; 
} else { 
current_image++; 
} 
selector = $('[data-image-id="' + current_image + '"]'); 
updateGallery(selector); 
}); 
46 
function updateGallery(selector) { 
var $sel = selector; 
current_image = $sel.data('image-id'); 
$('#image-gallery-caption').text($sel.data('caption')); 
$('#image-gallery-title').text($sel.data('title')); 
$('#image-gallery-image').attr('src', $sel.data('image')); 
disableButtons(counter, $sel.data('image-id')); 
} 
if(setIDs == true){ 
$('[data-image-id]').each(function(){ 
counter++; 
$(this).attr('data-image-id',counter); 
}); 
} 
$(setClickAttr).on('click',function(){ 
updateGallery($(this)); 
}); 
} 
}); 
</script> 
<!--footer--> 
<div class="footer"> 
<div class="footer-middle"> 
<div class="container"> 
<div class="footer-bottom-top component"> 
<ul class="social-ic"> 
<li><a href="#"><i></i></a></li> 
<li><a href="#"><i class="ic"></i></a></li> 
<li><a href="#"><i class="ic1"></i></a></li> 
<li><a href="#"><i class="ic2"></i></a></li> 
<li><a href="#"><i class="ic3"></i></a></li> 
</ul> 
47 
</div> 
<p class="footer-class animated wow fadeInUp" data- 
wow-duration="1000ms" data-wow-delay="500ms">&copy; 2019 Hierarchal Transmission. 
All Rights Reserved | Design by <a href="#">Admin</a></p> 
<div class="clearfix"> </div> 
</div> 
</div> 
</div> 
<!--//footer--> 
<!-- animation-effect --> 
<link href="css/animate.min.css" rel="stylesheet"> 
<script src="js/wow.min.js"></script> 
<script> 
new WOW().init(); 
</script> 
<!-- //animation-effect --> 
</body> 
</html>
