
<!--A Design by W3layouts 
Author: W3layout 
Author URL: http://w3layouts.com 
License: Creative Commons Attribution 3.0 Unported 
License URL: http://creativecommons.org/licenses/by/3.0/ --> 
<!DOCTYPE html> 
<html> 
<head> 
<link rel="icon" href="images/logo222.png" type="image/gif" sizes="16x16"> 
<title>Data Encryption</title> 
<link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="all" /> 
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
<script src="js/jquery.min.js"></script> 
<!-- Custom Theme files --> 
<!--theme-style--> 
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" /> 
<!--//theme-style--> 
<meta name="viewport" content="width=device-width, initial-scale=1"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<meta name="keywords" content="Spa Center Responsive web template, Bootstrap Web 
Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns 
SonyEricsson, Motorola web design" /> 
<script 
type="application/x-javascript"> 
for Nokia, Samsung, LG, 
addEventListener("load", 
function() 
{ 
setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } 
</script> 
25 
<!----> 
<script src="js/bootstrap.min.js"></script> 
<link href='//fonts.googleapis.com/css?family=Lora:400,700' rel='stylesheet' type='text/css'> 
<link 
href='//fonts.googleapis.com/css?family=Raleway:400,200,100,300,500,600,700,800,900' 
rel='stylesheet' type='text/css'> 
<link rel="stylesheet" type="text/css" href="css/component.css" /> 
<style> 
.style1 {color:#000000; font-weight:bold;} 
</style> 
</head> 
<body> 
<div class="header"> 
<nav class="navbar navbar-default animated wow fadeInLeft" data-wow- 
duration="1000ms" data-wow-delay="500ms"> 
<div class="container"> 
<div class="container-fluid"> 
<!-- Brand and toggle get grouped for better mobile display --> 
<div class="navbar-header"> 
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> 
<span class="sr-only">Toggle navigation</span> 
<span class="icon-bar"></span> 
<span class="icon-bar"></span> 
<span class="icon-bar"></span> 
</button> 
</div> 
<!-- Collect the nav links, forms, and other content for toggling --> 
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> 
<form class="navbar-form navbar-left" role="search"> 
<div class="form-group"> 
26 
<input 
type="text" 
class="form-control 
form-cont" 
value="Search" 
onFocus="this.value='';" onBlur="if (this.value == '') {this.value ='Search';}"> 
</div> 
<button type="submit" class="btn-search"></button> 
</form> 
<ul class="nav navbar-nav cl-effect-8"> 
<li ><a class="active" href="index.php">Home </a></li> 
<li><a href="ulogin.php">User</a></li> 
<li><a href="alogin.php">Admin</a></li> 
<li><a href="#">About</a></li> 
<li><a href="contact.php">Contact</a></li> 
</ul> 
</div><!-- /.navbar-collapse --> 
</div><!-- /.container-fluid --> 
</div> 
</nav> 
<!-- start search--> 
<div class="logo animated wow shake" data-wow-duration="1000ms" data- 
wow-delay="500ms"> 
<a href="index.html"><img src="images/logo1.png" alt=""></a> 
</div> 
<div class="banner animated wow fadeInDown" data-wow-duration="1000ms" 
data-wow-delay="500ms"> 
<p>Data Encryption and Decryption</p> 
<a href="single.html" class="hvr-sweep-to-bottom">Read More</a> 
<label></label> 
</div> 
</div> 
<!--contact--> 
<div class="content"> 
<div class="container"> 
<div class="content-top-top"> 
<div class="col-top"> 
27 
<h1>Message Conversation Security</h1> 
<div class="content-mid"> 
<div class="col-md-6 content-img animated wow 
fadeInLeft" data-wow-duration="1000ms" data-wow-delay="500ms"> 
<a href="single.html" rel="title" class="b-link- 
stripe b-animate-go thickbox"> 
<img 
class="img-responsive" 
src="images/pi.jpg" /> 
from-left b-delay03 "> 
<span>Encryption</span> 
</a>  
<div class="b-wrapper"> 
<h4  class="b-animate  b- 
</h4> 
</div> 
</div> 
<div class="col-md-6 content-img animated wow 
fadeInRight" data-wow-duration="1000ms" data-wow-delay="500ms"> 
<a href="single.html" rel="title" class="b-link- 
stripe b-animate-go thickbox"> 
<img 
class="img-responsive" 
src="images/pi1.jpg" /> 
from-left b-delay03 "> 
<span>Decryption</span> 
</a>  
<div class="b-wrapper"> 
<h4  class="b-animate  b- 
</div> 
</div> 
</h4> 
28 
<div class="clearfix"></div> 
</div> 
<div class="content-top"> 
<div class="col-md-6 content-top-2"> 
<p align="justify"><strong> Encryption is 
the process of using an algorithm to transform information to make it unreadable for 
unauthorized users. This cryptographic method protects sensitive data such as credit card 
numbers by encoding and transforming information into unreadable cipher text. This encoded 
data may only be decrypted or made readable with a key. Symmetric-key and asymmetric-key 
are the two primary types of encryption.</strong></p> 
</div> 
<div class="col-md-6 content-top-1"> 
<p 
align="justify"><strong>The 
conversion of encrypted data into its original form is called Decryption. It is generally a reverse 
process of encryption. It decodes the encrypted information so that an authorized user can only 
decrypt the data because decryption requires a secret key or password.One of the reasons for 
implementing an encryption-decryption system is privacy.There are many methods of 
conventional cryptography.</strong></p> 
</div> 
<div class="clearfix"></div> 
</div> 
</div> 
</div> 
</div> 
<!----> 
<div class="choose-us"> 
<div class="container"> 
<h2>Techniques</h2> 
<div class="servies-top"> 
<div class="col-md-6 us-choose animated wow fadeInUp" data-wow- 
duration="1000ms" data-wow-delay="500ms"> 
<div class=" why-choose"> 
29 
<div class=" hi-icon-effect-6"> 
<a href="#set-6" class="hi-icon glyphicon 
glyphicon-cog"></a>  
</div> 
<div class="ser-top "> 
<h5> ABOUT CLOUD COMPUTING </h5> 
<label></label> 
<p 
align="justify">The benefits of cloud 
computing services include the ability to scale elastically. In cloud speak, that means delivering 
the right amount of IT resources.</p> 
</div> 
<div class="clearfix"> </div> 
</div> 
<div class=" why-choose"> 
<div class=" hi-icon-effect-6"> 
<a href="#set-6" class="hi-icon 
glyphicon-leaf"></a> 
</div> 
<div class="ser-top"> 
glyphicon 
<h5>ABOUT CRYPTOGRAPHY </h5> 
<label></label> 
<p 
align="justify">Cryptography 
involves 
creating written or generated codes that allow information to be kept secret. Cryptography 
converts data into a format that is unreadable for an unauthorized user.</p> 
</div> 
<div class="clearfix"> </div> 
</div> 
<div class=" why-choose"> 
<div class=" hi-icon-effect-6"> 
<a href="#set-6" class="hi-icon 
glyphicon-star"></a> 
</div> 
<div class="ser-top"> 
glyphicon 
30 
<h5>ABOUT DIFFIE-HELLMEN </h5> 
<label></label> 
<p align="justify">Diffie-Hellman key exchange, 
also called exponential key exchange, is a method of digital encryption that uses numbers raised 
to specific powers to produce decryption keys.</p> 
</div> 
<div class="clearfix"> </div> 
</div> 
</div> 
<div class="col-md-6 us-choose animated wow fadeInUp" data-wow- 
duration="1000ms" data-wow-delay="500ms"> 
<div class=" why-choose"> 
<div class=" hi-icon-effect-6"> 
<a href="#set-6" class="hi-icon glyphicon 
glyphicon-edit"></a>  
 
</div> 
<div class="ser-top "> 
<h5>ABOUT ECC ALGORITHM </h5> 
<label></label> 
<p align="justify">ECC key is very helpful for 
the current generation as more people are moving to the Smartphone. As the utilization is an 
emerging need for a more flexible encryption.</p> 
</div> 
<div class="clearfix"> </div> 
</div> 
<div class=" why-choose"> 
<div class=" hi-icon-effect-6"> 
<a href="#set-6" class="hi-icon 
glyphicon-user"></a> 
</div> 
<div class="ser-top"> 
<h5>ABOUT PHP</h5> 
<label></label> 
glyphicon 
31 
<p align="justify">PHP is a recursive acronym 
for PHP: Hypertext Preprocessor, a scripting language used to create dynamic and interactive 
HTML Web pages. A server processes.</p> 
</div> 
<div class="clearfix"> </div> 
</div> 
<div class=" why-choose"> 
<div class=" hi-icon-effect-6"> 
<a href="#set-6" class="hi-icon 
glyphicon-refresh"></a> 
</div> 
<div class="ser-top"> 
<h5>ABOUT MYSQL </h5> 
<label></label> 
glyphicon 
<p align="justify">MySQL is a full-featured 
relational database management system (RDBMS) that competes with the likes of Oracle DB 
and Microsoft’s SQL Server.</p> 
</div> 
</div> 
</div> 
<div class="clearfix"> </div> 
<div class="clearfix"> </div> 
</div> 
</div> 
</div> 
<!----> 
<div class="events"> 
<div class="container"> 
<div class="event-text"> 
<h3>Data Transmission </h3> 
</div> 
<div class=" events-grid-1" > 
32 
<div class="col-md-4 ev-wrapper animated wow fadeInLeft" 
data-wow-duration="1000ms" data-wow-delay="500ms"> 
<a href="single.html"> 
<div class="ev-wrap"> 
<img  src="images/ev.jpg"  alt=""  class="img- 
responsive" />  
 
<div class="events-grid"> 
<h6>Work</h6> 
<div class="events-gr"> 
<span>PublicKey</span> 
<h4>Data Encryption</h4> 
</div> 
</div> 
<div class="grid-ev"></div> 
</div> 
</a> 
</div> 
<div class="col-md-4 ev-wrapper animated wow fadeInDown" 
data-wow-duration="1000ms" data-wow-delay="500ms"> 
<a href="single.html"> 
<div class="ev-wrap"> 
<img src="images/ev2.jpg" alt="" class="img- 
responsive" />  
 
<div class="events-grid"> 
<h6>Work</h6> 
<div class="events-gr"> 
<span>CipherText</span> 
<h4>PlainText</h4> 
</div> 
</div> 
<div class="grid-ev"></div> 
</div> 
33 
</a> 
</div> 
<div class="col-md-4 ev-wrapper animated wow fadeInUp" 
data-wow-duration="1000ms" data-wow-delay="500ms"> 
<a href="single.html"> 
<div class="ev-wrap"> 
<img src="images/ev1.jpg" alt="" class="img- 
responsive" />  
</div> 
</div> 
<!----> 
<!--footer--> 
<div class="footer"> 
<div class="events-grid"> 
<h6>Work</h6> 
<div class="events-gr"> 
<span>PrivateKey</span> 
<h4>Data Decryption</h4> 
</div> 
</div> 
<div class="grid-ev"></div> 
</div> 
</a> 
</div> 
<div class="clearfix"> </div> 
</div> 
</div> 
<div class="footer-middle"> 
<div class="container"> 
<div class="footer-bottom-top component"> 
<ul class="social-ic"> 
<li><a href="#"><i></i></a></li> 
<li><a href="#"><i class="ic"></i></a></li> 
34 
<li><a href="#"><i class="ic1"></i></a></li> 
<li><a href="#"><i class="ic2"></i></a></li> 
<li><a href="#"><i class="ic3"></i></a></li> 
</ul> 
</div> 
<p class="footer-class animated wow fadeInUp" data- 
wow-duration="1000ms" data-wow-delay="500ms">&copy; 2019 Hierarchal Transmission. 
All Rights Reserved | Design by <a href="#">Admin</a> </p> 
<div class="clearfix"> </div> 
</div> 
</div> 
</div> 
<!--//footer--> 
<!-- animation-effect --> 
<link href="css/animate.min.css" rel="stylesheet"> 
<script src="js/wow.min.js"></script> 
<script> 
new WOW().init(); 
</script> 
<!-- //animation-effect --> 
</body> 
</html> 
